# Generated by Django 3.2.6 on 2021-08-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matchFinder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='job',
            name='choice_text',
        ),
        migrations.RemoveField(
            model_name='job',
            name='votes',
        ),
    ]
