# Generated by Django 3.2.6 on 2021-08-08 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matchFinder', '0002_auto_20210808_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchFinder.job')),
                ('skill_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchFinder.skill')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatesAbilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchFinder.candidate')),
                ('skill_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchFinder.skill')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='skills',
            field=models.ManyToManyField(through='matchFinder.CandidatesAbilities', to='matchFinder.Skill'),
        ),
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(through='matchFinder.JobRequirements', to='matchFinder.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='candidates',
            field=models.ManyToManyField(through='matchFinder.CandidatesAbilities', to='matchFinder.Candidate'),
        ),
        migrations.AddField(
            model_name='skill',
            name='jobs',
            field=models.ManyToManyField(through='matchFinder.JobRequirements', to='matchFinder.Job'),
        ),
    ]
