# Generated by Django 3.2.6 on 2021-08-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchFinder', '0003_auto_20210808_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='name',
            field=models.CharField(default='candidate', max_length=200),
        ),
    ]
